
version: '3'
services: 
  api:
    container_name: api-container
    restart: always
    build: ./ecommerce
    ports: 
      - "8000:8000"
    depends_on: 
      - mongo
  mongo:
    container_name: mongo-backend
    image: mongo:4.4.6
    expose: 
      - "27017"
    ports: 
      - "27017:27017"
    volumes:
      - db-data:/data/db
volumes: 
  db-data:

